generator:
  class: sfDoctrineGenerator
  param:
    model_class:           citation
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          citation
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Liste des citations
        display: [=author,=content]
        fields:
          author:
            label: Auteur
          content:
            label: Citation
        batch_actions: {}
      filter:
        class: false
      form:    ~
      edit:
        title: Modifier une citation
      new:
        title: Ajouter une citation
