<?php

/**
 * BaseBilanCarboneCoeff
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name_short
 * @property string $name
 * @property float $coeff
 * 
 * @method string            getNameShort()  Returns the current record's "name_short" value
 * @method string            getName()       Returns the current record's "name" value
 * @method float             getCoeff()      Returns the current record's "coeff" value
 * @method BilanCarboneCoeff setNameShort()  Sets the current record's "name_short" value
 * @method BilanCarboneCoeff setName()       Sets the current record's "name" value
 * @method BilanCarboneCoeff setCoeff()      Sets the current record's "coeff" value
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseBilanCarboneCoeff extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bilan_carbone_coeff');
        $this->hasColumn('name_short', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('coeff', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}