<?php

/**
 * BaseCorespondance
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property datetime $first_mail
 * @property datetime $last_mail
 * @property integer $number_of_mail
 * @property Doctrine_Collection $Person
 * 
 * @method datetime            getFirstMail()      Returns the current record's "first_mail" value
 * @method datetime            getLastMail()       Returns the current record's "last_mail" value
 * @method integer             getNumberOfMail()   Returns the current record's "number_of_mail" value
 * @method Doctrine_Collection getPerson()         Returns the current record's "Person" collection
 * @method Corespondance       setFirstMail()      Sets the current record's "first_mail" value
 * @method Corespondance       setLastMail()       Sets the current record's "last_mail" value
 * @method Corespondance       setNumberOfMail()   Sets the current record's "number_of_mail" value
 * @method Corespondance       setPerson()         Sets the current record's "Person" collection
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseCorespondance extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('corespondance');
        $this->hasColumn('first_mail', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('last_mail', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('number_of_mail', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Person', array(
             'local' => 'id',
             'foreign' => 'corespondance_id'));
    }
}