<?php

/**
 * BaseGoogleAnalytics
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $code
 * 
 * @method text            getCode() Returns the current record's "code" value
 * @method GoogleAnalytics setCode() Sets the current record's "code" value
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseGoogleAnalytics extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('google_analytics');
        $this->hasColumn('code', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}