<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $position
 * @property boolean $is_activated
 * @property Doctrine_Collection $Page
 * @property Doctrine_Collection $StaticPage
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method integer             getPosition()     Returns the current record's "position" value
 * @method boolean             getIsActivated()  Returns the current record's "is_activated" value
 * @method Doctrine_Collection getPage()         Returns the current record's "Page" collection
 * @method Doctrine_Collection getStaticPage()   Returns the current record's "StaticPage" collection
 * @method Category            setName()         Sets the current record's "name" value
 * @method Category            setPosition()     Sets the current record's "position" value
 * @method Category            setIsActivated()  Sets the current record's "is_activated" value
 * @method Category            setPage()         Sets the current record's "Page" collection
 * @method Category            setStaticPage()   Sets the current record's "StaticPage" collection
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('name', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 40,
             ));
        $this->hasColumn('position', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Page', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('StaticPage', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}