<?php

/**
 * BaseSlogan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property enum $type
 * @property enum $flag
 * @property string $content
 * @property Doctrine_Collection $Counter
 * @property Doctrine_Collection $RefImageParam
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method enum                getType()          Returns the current record's "type" value
 * @method enum                getFlag()          Returns the current record's "flag" value
 * @method string              getContent()       Returns the current record's "content" value
 * @method Doctrine_Collection getCounter()       Returns the current record's "Counter" collection
 * @method Doctrine_Collection getRefImageParam() Returns the current record's "RefImageParam" collection
 * @method Slogan              setName()          Sets the current record's "name" value
 * @method Slogan              setType()          Sets the current record's "type" value
 * @method Slogan              setFlag()          Sets the current record's "flag" value
 * @method Slogan              setContent()       Sets the current record's "content" value
 * @method Slogan              setCounter()       Sets the current record's "Counter" collection
 * @method Slogan              setRefImageParam() Sets the current record's "RefImageParam" collection
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseSlogan extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('slogan');
        $this->hasColumn('name', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'counter',
              1 => 'refimg',
             ),
             ));
        $this->hasColumn('flag', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'position 1',
              1 => 'position 2',
              2 => 'position 3',
             ),
             ));
        $this->hasColumn('content', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));


        $this->index('nameflag', array(
             'type' => 'unique',
             'fields' => 
             array(
              0 => 'name',
              1 => 'flag',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Counter', array(
             'local' => 'name',
             'foreign' => 'slogan'));

        $this->hasMany('RefImageParam', array(
             'local' => 'name',
             'foreign' => 'slogan'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'content',
             ),
             ));
        $this->actAs($i18n0);
    }
}