<?php

/**
 * BaseNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $title
 * @property text $content
 * @property boolean $is_activated
 * @property integer $language_id
 * @property timestamp $publication_date
 * @property boolean $comments_activated
 * @property Language $Language
 * @property Doctrine_Collection $NewsComments
 * 
 * @method varchar             getTitle()              Returns the current record's "title" value
 * @method text                getContent()            Returns the current record's "content" value
 * @method boolean             getIsActivated()        Returns the current record's "is_activated" value
 * @method integer             getLanguageId()         Returns the current record's "language_id" value
 * @method timestamp           getPublicationDate()    Returns the current record's "publication_date" value
 * @method boolean             getCommentsActivated()  Returns the current record's "comments_activated" value
 * @method Language            getLanguage()           Returns the current record's "Language" value
 * @method Doctrine_Collection getNewsComments()       Returns the current record's "NewsComments" collection
 * @method News                setTitle()              Sets the current record's "title" value
 * @method News                setContent()            Sets the current record's "content" value
 * @method News                setIsActivated()        Sets the current record's "is_activated" value
 * @method News                setLanguageId()         Sets the current record's "language_id" value
 * @method News                setPublicationDate()    Sets the current record's "publication_date" value
 * @method News                setCommentsActivated()  Sets the current record's "comments_activated" value
 * @method News                setLanguage()           Sets the current record's "Language" value
 * @method News                setNewsComments()       Sets the current record's "NewsComments" collection
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseNews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news');
        $this->hasColumn('title', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('content', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('language_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('publication_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('comments_activated', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Language', array(
             'local' => 'language_id',
             'foreign' => 'id'));

        $this->hasMany('NewsComments', array(
             'local' => 'id',
             'foreign' => 'news_id'));
    }
}