<?php

/**
 * BaseSubscriber
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $email
 * @property string $hash
 * 
 * @method string     getEmail() Returns the current record's "email" value
 * @method string     getHash()  Returns the current record's "hash" value
 * @method Subscriber setEmail() Sets the current record's "email" value
 * @method Subscriber setHash()  Sets the current record's "hash" value
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseSubscriber extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subscriber');
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('hash', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}