<?php

/**
 * BaseNewsComments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $content
 * @property integer $author_id
 * @property integer $news_id
 * @property integer $father_id
 * @property News $News
 * @property sfGuardUser $sfGuardUser
 * 
 * @method text         getContent()     Returns the current record's "content" value
 * @method integer      getAuthorId()    Returns the current record's "author_id" value
 * @method integer      getNewsId()      Returns the current record's "news_id" value
 * @method integer      getFatherId()    Returns the current record's "father_id" value
 * @method News         getNews()        Returns the current record's "News" value
 * @method sfGuardUser  getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method NewsComments setContent()     Sets the current record's "content" value
 * @method NewsComments setAuthorId()    Sets the current record's "author_id" value
 * @method NewsComments setNewsId()      Sets the current record's "news_id" value
 * @method NewsComments setFatherId()    Sets the current record's "father_id" value
 * @method NewsComments setNews()        Sets the current record's "News" value
 * @method NewsComments setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseNewsComments extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news_comments');
        $this->hasColumn('content', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('author_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('news_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('father_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('News', array(
             'local' => 'news_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'author_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}