<?php

/**
 * BaseConfiguration
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property text $description
 * @property integer $configuration_id
 * @property Configuration $Configuration
 * 
 * @method string        getName()             Returns the current record's "name" value
 * @method text          getDescription()      Returns the current record's "description" value
 * @method integer       getConfigurationId()  Returns the current record's "configuration_id" value
 * @method Configuration getConfiguration()    Returns the current record's "Configuration" value
 * @method Configuration setName()             Sets the current record's "name" value
 * @method Configuration setDescription()      Sets the current record's "description" value
 * @method Configuration setConfigurationId()  Sets the current record's "configuration_id" value
 * @method Configuration setConfiguration()    Sets the current record's "Configuration" value
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseConfiguration extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('configuration');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('configuration_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Configuration', array(
             'local' => 'configuration_id',
             'foreign' => 'id'));
    }
}