<?php

/**
 * BaseRefImageParam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property integer $text1
 * @property integer $text2
 * @property integer $text3
 * @property RefTextParam $RefTextParam
 * @property Doctrine_Collection $RefImage
 * 
 * @method string              getUrl()          Returns the current record's "url" value
 * @method integer             getText1()        Returns the current record's "text1" value
 * @method integer             getText2()        Returns the current record's "text2" value
 * @method integer             getText3()        Returns the current record's "text3" value
 * @method RefTextParam        getRefTextParam() Returns the current record's "RefTextParam" value
 * @method Doctrine_Collection getRefImage()     Returns the current record's "RefImage" collection
 * @method RefImageParam       setUrl()          Sets the current record's "url" value
 * @method RefImageParam       setText1()        Sets the current record's "text1" value
 * @method RefImageParam       setText2()        Sets the current record's "text2" value
 * @method RefImageParam       setText3()        Sets the current record's "text3" value
 * @method RefImageParam       setRefTextParam() Sets the current record's "RefTextParam" value
 * @method RefImageParam       setRefImage()     Sets the current record's "RefImage" collection
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseRefImageParam extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ref_image_param');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('text1', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('text2', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('text3', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RefTextParam', array(
             'local' => 'text3',
             'foreign' => 'id',
             'onDelete' => 'SET NULL',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('RefImage', array(
             'local' => 'id',
             'foreign' => 'param_id'));
    }
}