<?php

/**
 * BaseNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $content
 * @property boolean $is_activated
 * @property integer $language_id
 * @property timestamp $publication_date
 * @property Language $Language
 * 
 * @method text      getContent()          Returns the current record's "content" value
 * @method boolean   getIsActivated()      Returns the current record's "is_activated" value
 * @method integer   getLanguageId()       Returns the current record's "language_id" value
 * @method timestamp getPublicationDate()  Returns the current record's "publication_date" value
 * @method Language  getLanguage()         Returns the current record's "Language" value
 * @method News      setContent()          Sets the current record's "content" value
 * @method News      setIsActivated()      Sets the current record's "is_activated" value
 * @method News      setLanguageId()       Sets the current record's "language_id" value
 * @method News      setPublicationDate()  Sets the current record's "publication_date" value
 * @method News      setLanguage()         Sets the current record's "Language" value
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseNews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news');
        $this->hasColumn('content', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('language_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('publication_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Language', array(
             'local' => 'language_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}