<?php

/**
 * BaseMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $text
 * @property boolean $is_saved
 * @property date $read_at
 * @property date $created_at
 * @property date $reply_at
 * @property integer $comment_id
 * @property Comment $Comment
 * 
 * @method text    getText()       Returns the current record's "text" value
 * @method boolean getIsSaved()    Returns the current record's "is_saved" value
 * @method date    getReadAt()     Returns the current record's "read_at" value
 * @method date    getCreatedAt()  Returns the current record's "created_at" value
 * @method date    getReplyAt()    Returns the current record's "reply_at" value
 * @method integer getCommentId()  Returns the current record's "comment_id" value
 * @method Comment getComment()    Returns the current record's "Comment" value
 * @method Message setText()       Sets the current record's "text" value
 * @method Message setIsSaved()    Sets the current record's "is_saved" value
 * @method Message setReadAt()     Sets the current record's "read_at" value
 * @method Message setCreatedAt()  Sets the current record's "created_at" value
 * @method Message setReplyAt()    Sets the current record's "reply_at" value
 * @method Message setCommentId()  Sets the current record's "comment_id" value
 * @method Message setComment()    Sets the current record's "Comment" value
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseMessage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('message');
        $this->hasColumn('text', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('is_saved', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('read_at', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('created_at', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('reply_at', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('comment_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Comment', array(
             'local' => 'comment_id',
             'foreign' => 'id'));
    }
}