<?php

/**
 * BaseRefTextParam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $x
 * @property integer $y
 * @property integer $width
 * @property integer $font_size
 * @property string $color
 * @property Doctrine_Collection $RefImageParam
 * 
 * @method integer             getX()             Returns the current record's "x" value
 * @method integer             getY()             Returns the current record's "y" value
 * @method integer             getWidth()         Returns the current record's "width" value
 * @method integer             getFontSize()      Returns the current record's "font_size" value
 * @method string              getColor()         Returns the current record's "color" value
 * @method Doctrine_Collection getRefImageParam() Returns the current record's "RefImageParam" collection
 * @method RefTextParam        setX()             Sets the current record's "x" value
 * @method RefTextParam        setY()             Sets the current record's "y" value
 * @method RefTextParam        setWidth()         Sets the current record's "width" value
 * @method RefTextParam        setFontSize()      Sets the current record's "font_size" value
 * @method RefTextParam        setColor()         Sets the current record's "color" value
 * @method RefTextParam        setRefImageParam() Sets the current record's "RefImageParam" collection
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseRefTextParam extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ref_text_param');
        $this->hasColumn('x', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('y', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('width', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('font_size', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('color', 'string', 6, array(
             'type' => 'string',
             'length' => 6,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('RefImageParam', array(
             'local' => 'id',
             'foreign' => 'text3'));
    }
}