<?php

/**
 * BasePhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $url
 * @property text $description
 * @property timestamp $publication_start
 * @property timestamp $publication_end
 * @property integer $galery_id
 * @property Galery $Galery
 * 
 * @method string    getTitle()             Returns the current record's "title" value
 * @method string    getUrl()               Returns the current record's "url" value
 * @method text      getDescription()       Returns the current record's "description" value
 * @method timestamp getPublicationStart()  Returns the current record's "publication_start" value
 * @method timestamp getPublicationEnd()    Returns the current record's "publication_end" value
 * @method integer   getGaleryId()          Returns the current record's "galery_id" value
 * @method Galery    getGalery()            Returns the current record's "Galery" value
 * @method Photo     setTitle()             Sets the current record's "title" value
 * @method Photo     setUrl()               Sets the current record's "url" value
 * @method Photo     setDescription()       Sets the current record's "description" value
 * @method Photo     setPublicationStart()  Sets the current record's "publication_start" value
 * @method Photo     setPublicationEnd()    Sets the current record's "publication_end" value
 * @method Photo     setGaleryId()          Sets the current record's "galery_id" value
 * @method Photo     setGalery()            Sets the current record's "Galery" value
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BasePhoto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('photo');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('publication_start', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('publication_end', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('galery_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Galery', array(
             'local' => 'galery_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'description',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}