<?php

/**
 * BaseBooleanConfiguration
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Configuration
 * @property Doctrine_Collection $DynamicPage
 * 
 * @method Doctrine_Collection  getConfiguration() Returns the current record's "Configuration" collection
 * @method Doctrine_Collection  getDynamicPage()   Returns the current record's "DynamicPage" collection
 * @method BooleanConfiguration setConfiguration() Sets the current record's "Configuration" collection
 * @method BooleanConfiguration setDynamicPage()   Sets the current record's "DynamicPage" collection
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseBooleanConfiguration extends Configuration
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Configuration', array(
             'local' => 'id',
             'foreign' => 'configuration_id'));

        $this->hasMany('DynamicPage', array(
             'local' => 'id',
             'foreign' => 'boolean_configuation_id'));
    }
}