<?php

/**
 * BaseGalery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $position
 * @property boolean $is_activated
 * @property Doctrine_Collection $Photo
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method integer             getPosition()     Returns the current record's "position" value
 * @method boolean             getIsActivated()  Returns the current record's "is_activated" value
 * @method Doctrine_Collection getPhoto()        Returns the current record's "Photo" collection
 * @method Galery              setName()         Sets the current record's "name" value
 * @method Galery              setPosition()     Sets the current record's "position" value
 * @method Galery              setIsActivated()  Sets the current record's "is_activated" value
 * @method Galery              setPhoto()        Sets the current record's "Photo" collection
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseGalery extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('galery');
        $this->hasColumn('name', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 40,
             ));
        $this->hasColumn('position', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Photo', array(
             'local' => 'id',
             'foreign' => 'galery_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($i18n0);
    }
}