<?php

/**
 * BaseDynamicPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $controller
 * @property string $action
 * @property integer $boolean_configuation_id
 * @property BooleanConfiguration $BooleanConfiguration
 * 
 * @method string               getController()              Returns the current record's "controller" value
 * @method string               getAction()                  Returns the current record's "action" value
 * @method integer              getBooleanConfiguationId()   Returns the current record's "boolean_configuation_id" value
 * @method BooleanConfiguration getBooleanConfiguration()    Returns the current record's "BooleanConfiguration" value
 * @method DynamicPage          setController()              Sets the current record's "controller" value
 * @method DynamicPage          setAction()                  Sets the current record's "action" value
 * @method DynamicPage          setBooleanConfiguationId()   Sets the current record's "boolean_configuation_id" value
 * @method DynamicPage          setBooleanConfiguration()    Sets the current record's "BooleanConfiguration" value
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseDynamicPage extends Page
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('dynamic_page');
        $this->hasColumn('controller', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('action', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('boolean_configuation_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BooleanConfiguration', array(
             'local' => 'boolean_configuation_id',
             'foreign' => 'id'));
    }
}