<?php

/**
 * BaseCitation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $author
 * @property text $content
 * 
 * @method string   getAuthor()  Returns the current record's "author" value
 * @method text     getContent() Returns the current record's "content" value
 * @method Citation setAuthor()  Sets the current record's "author" value
 * @method Citation setContent() Sets the current record's "content" value
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseCitation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('citation');
        $this->hasColumn('author', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('content', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'author',
              1 => 'content',
             ),
             ));
        $this->actAs($i18n0);
    }
}