<?php

/**
 * BaseGuestbook
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $content
 * @property boolean $is_validated
 * @property integer $language_id
 * @property Language $Language
 * 
 * @method text      getContent()      Returns the current record's "content" value
 * @method boolean   getIsValidated()  Returns the current record's "is_validated" value
 * @method integer   getLanguageId()   Returns the current record's "language_id" value
 * @method Language  getLanguage()     Returns the current record's "Language" value
 * @method Guestbook setContent()      Sets the current record's "content" value
 * @method Guestbook setIsValidated()  Sets the current record's "is_validated" value
 * @method Guestbook setLanguageId()   Sets the current record's "language_id" value
 * @method Guestbook setLanguage()     Sets the current record's "Language" value
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseGuestbook extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('guestbook');
        $this->hasColumn('content', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('is_validated', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('language_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Language', array(
             'local' => 'language_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}