<?php

/**
 * BaseFolder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Message
 * 
 * @method string              getName()    Returns the current record's "name" value
 * @method Doctrine_Collection getMessage() Returns the current record's "Message" collection
 * @method Folder              setName()    Sets the current record's "name" value
 * @method Folder              setMessage() Sets the current record's "Message" collection
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseFolder extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('folder');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Message', array(
             'local' => 'id',
             'foreign' => 'folder_id'));
    }
}