<?php

/**
 * BaseNumericConfiguration
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $value
 * 
 * @method integer              getValue() Returns the current record's "value" value
 * @method NumericConfiguration setValue() Sets the current record's "value" value
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseNumericConfiguration extends Configuration
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('numeric_configuration');
        $this->hasColumn('value', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}