<?php

/**
 * BaseFaq
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $question
 * @property text $answer
 * @property integer $position
 * @property boolean $is_activated
 * @property integer $faq_category_id
 * 
 * @method text    getQuestion()        Returns the current record's "question" value
 * @method text    getAnswer()          Returns the current record's "answer" value
 * @method integer getPosition()        Returns the current record's "position" value
 * @method boolean getIsActivated()     Returns the current record's "is_activated" value
 * @method integer getFaqCategoryId()   Returns the current record's "faq_category_id" value
 * @method Faq     setQuestion()        Sets the current record's "question" value
 * @method Faq     setAnswer()          Sets the current record's "answer" value
 * @method Faq     setPosition()        Sets the current record's "position" value
 * @method Faq     setIsActivated()     Sets the current record's "is_activated" value
 * @method Faq     setFaqCategoryId()   Sets the current record's "faq_category_id" value
 * @property  $
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseFaq extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('faq');
        $this->hasColumn('question', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('answer', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('position', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('faq_category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('faqCategory', array(
             'local' => 'faq_category_id',
             'foreign' => 'id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'question',
              1 => 'answer',
              2 => 'is_activated',
             ),
             ));
        $this->actAs($i18n0);
    }
}