<?php

/**
 * BaseCounterText
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $slogan1
 * @property string $slogan2
 * @property string $donation
 * 
 * @method string      getSlogan1()  Returns the current record's "slogan1" value
 * @method string      getSlogan2()  Returns the current record's "slogan2" value
 * @method string      getDonation() Returns the current record's "donation" value
 * @method CounterText setSlogan1()  Sets the current record's "slogan1" value
 * @method CounterText setSlogan2()  Sets the current record's "slogan2" value
 * @method CounterText setDonation() Sets the current record's "donation" value
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseCounterText extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('counter_text');
        $this->hasColumn('slogan1', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('slogan2', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('donation', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'slogan1',
              1 => 'slogan2',
              2 => 'donation',
             ),
             ));
        $this->actAs($i18n0);
    }
}