newsletter:
  class: sfDoctrineRouteCollection
  options:
    model:                Newsletter
    module:               newsletter
    prefix_path:          /newsletter
    column:               id
    with_wildcard_routes: true

donenligne:
  class: sfDoctrineRouteCollection
  options:
    model:                payment
    module:               donenligne
    prefix_path:          /donenligne
    column:               id
    with_wildcard_routes: true
payment:
  class: sfDoctrineRouteCollection
  options:
    model:                payment
    module:               donenligne
    prefix_path:          /donenligne
    column:               id
    with_wildcard_routes: true

standard_sentence:
  class: sfDoctrineRouteCollection
  options:
    model:                StandardSentence
    module:               sentences
    prefix_path:          /sentences
    column:               id
    with_wildcard_routes: true

folder:
  class: sfDoctrineRouteCollection
  options:
    model:                Folder
    module:               folder
    prefix_path:          /folder
    column:               id
    with_wildcard_routes: true

dynamic_page:
  class: sfDoctrineRouteCollection
  options:
    model:                DynamicPage
    module:               dynamic_page
    prefix_path:          /dynamic_page
    column:               id
    with_wildcard_routes: true

counter:
  class: sfDoctrineRouteCollection
  options:
    model:                Counter
    module:               counter
    prefix_path:          /counter
    column:               id
    with_wildcard_routes: true

news:
  class: sfDoctrineRouteCollection
  options:
    model:                News
    module:               news
    prefix_path:          /news
    column:               id
    with_wildcard_routes: true

guestbook:
  class: sfDoctrineRouteCollection
  options:
    model:                Guestbook
    module:               guestbook
    prefix_path:          /guestbook
    column:               id
    with_wildcard_routes: true

contactavances:
  class: sfDoctrineRouteCollection
  options:
    model:                Message
    module:               contactavances
    prefix_path:          /contactavances
    url:                  /contactavances
    column:               id
    with_wildcard_routes: true

faq_category:
  class: sfDoctrineRouteCollection
  options:
    model:                faqCategory
    module:               faq_category
    prefix_path:          /faq_category
    column:               id
    with_wildcard_routes: true

faq:
  class: sfDoctrineRouteCollection
  options:
    model:                faq
    module:               faq
    prefix_path:          /faq
    column:               id
    with_wildcard_routes: true

galery:
  class: sfDoctrineRouteCollection
  options:
    model:                Galery
    module:               galery
    prefix_path:          /galery
    column:               id
    with_wildcard_routes: true

photo:
  class: sfDoctrineRouteCollection
  options:
    model:                Photo
    module:               photo
    prefix_path:          /photo
    column:               id
    with_wildcard_routes: true

partner:
  class: sfDoctrineRouteCollection
  options:
    model:                partner
    module:               partner
    prefix_path:          /partner
    column:               id
    with_wildcard_routes: true

citation:
  class: sfDoctrineRouteCollection
  options:
    model:                citation
    module:               citation
    prefix_path:          /citation
    column:               id
    with_wildcard_routes: true

static_page:
  class: sfDoctrineRouteCollection
  options:
    model:                StaticPage
    module:               staticpage
    prefix_path:          /staticpage
    column:               id
    with_wildcard_routes: true

change_folder:
  url: /contactavances/changeFolder
  param: {module: contactavances, action: changeFolder}

delegate_to:
  url: /contactavances/delegateTo
  param: {module: contactavances, action: delegateTo}

insert_from_faq:
  url: /contactavances/InsertFromFaq
  param: {module: contactavances, action: InsertFromFaq}

sf_guard_permissions:
  url: /permission
  param: {module: sfGuardPermission, action: index}

sf_guard_group:
  url: /group
  param: {module: sfGuardGroup, action: index}

sf_guard_user_add:
  url: /user/add
  param: {module: sfGuardUser, action: new}

category:
  class: sfDoctrineRouteCollection
  options:
    model:                category
    module:               category
    prefix_path:          /category
    column:               id
    with_wildcard_routes: true

language:
  class: sfDoctrineRouteCollection
  options:
    model:                language
    module:               language
    prefix_path:          /language
    column:               id
    with_wildcard_routes: true

configuration:
  url: /configuration
  param: { module: configuration, action: index }

configuration_update:
  url: /configuration/update
  param: { module: configuration, action: update }

sentences:
  url: /sentence
  param: { module: sentences, action: index }

homepage:
  url:   /
  param: { module: homepage, action: index }
  
multiplephoto:
  url:   /multiplephoto
  param: { module: multiplephoto, action: index }  

