
message:
  class: sfDoctrineRouteCollection
  options:
    model:                message
    module:               message
    prefix_path:          /message

faq_category:
  class: sfDoctrineRouteCollection
  options:
    model:                faqCategory
    module:               faq_category
    prefix_path:          /faq_category
    column:               id
    with_wildcard_routes: true

faq:
  class: sfDoctrineRouteCollection
  options:
    model:                faq
    module:               faq
    prefix_path:          /faq
    column:               id
    with_wildcard_routes: true

galery:
  class: sfDoctrineRouteCollection
  options:
    model:                Galery
    module:               galery
    prefix_path:          /galery
    column:               id
    with_wildcard_routes: true

photo:
  class: sfDoctrineRouteCollection
  options:
    model:                Photo
    module:               photo
    prefix_path:          /photo
    column:               id
    with_wildcard_routes: true

partner:
  class: sfDoctrineRouteCollection
  options:
    model:                partner
    module:               partner
    prefix_path:          /partner
    column:               id
    with_wildcard_routes: true

citation:
  class: sfDoctrineRouteCollection
  options:
    model:                citation
    module:               citation
    prefix_path:          /citation
    column:               id
    with_wildcard_routes: true

static_page:
  class: sfDoctrineRouteCollection
  options:
    model:                StaticPage
    module:               staticpage
    prefix_path:          /staticpage
    column:               id
    with_wildcard_routes: true

sf_guard_permissions:
  url: /permission
  param: {module: sfGuardPermission, action: index}

sf_guard_group:
  url: /group
  param: {module: sfGuardGroup, action: index}

sf_guard_user_add:
  url: /user/add
  param: {module: sfGuardUser, action: new}

category:
  class: sfDoctrineRouteCollection
  options:
    model:                category
    module:               category
    prefix_path:          /category
    column:               id
    with_wildcard_routes: true

language:
  class: sfDoctrineRouteCollection
  options:
    model:                language
    module:               language
    prefix_path:          /language
    column:               id
    with_wildcard_routes: true

configuration:
  url: /configuration
  param: { module: configuration, action: index }

configuration_update:
  url: /configuration/update
  param: { module: configuration, action: update }


homepage:
  url:   /
  param: { module: homepage, action: index }

