language:
  class: sfDoctrineRouteCollection
  options:
    model:                language
    module:               language
    prefix_path:          /language
    column:               id
    with_wildcard_routes: true
configuration:
  url: /configuration
  param: { module: configuration, action: index }
configuration_update:
  url: /configuration/update
  param: { module: configuration, action: update }
homepage:
  url:   /
  param: { module: homepage, action: index }

