language:
  class: sfDoctrineRouteCollection
  options:
    model:                language
    module:               language
    prefix_path:          /language
    column:               id
    with_wildcard_routes: true
configuration:
  url: /configuration
  param: { module: configuration, action: index }
homepage:
  url:   /
  param: { module: language, action: index }

