# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:         Administration du site - Graine de vie
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [admin.css, jquery-ui-1.8.10.custom.css, uidatepicker.css]

  javascripts:    [lib/jquery-1.5.1.min.js, lib/jquery-ui-1.8.10.custom.min.js, lib/uidatepicker-fr.js]

  has_layout:     true
  layout:         layout
