generator:
  class: sfDoctrineGenerator
  param:
    model_class:           StandardSentence
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          standard_sentence
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        title: {label: 'Titre'}
        text: {label: 'Texte'}
      list:    
        display: [=title, text]
        title: Liste des phrases types
      filter:  ~
      form:    ~
      edit:    
        title: Modifier une phrase type
      new:     
        title: Nouvelle phrase type