generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Photo
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          photo
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:        
        title: {label: Titre}
        description: {label: Déscription}
        galery_id: {label: Gallérie}
        galery: {label: Gallérie}
        publication_start: {label: Debut de publication}
        publication_end: {label: Fin de publication}
        created_at: {label: Creer le: }
        updated_at: {label: Modifier le: }
        
      list:    
        title: Liste de Photos
        batch_actions: {}
        display: [_picsmall, title, description, galery, publication_start, publication_end]
        sort: [title, asc]
        table_method: retrieveBackendPhoto
      filter:  ~
      form: ~
      edit:    
        title: Edition de la photo
      new:
        title: Ajout d'une photo
