generator:
  class: sfDoctrineGenerator
  param:
    model_class:           StaticPage
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          static_page
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:

      actions: ~

      fields:
        publication_date: {label: Date de publication}
        menu_title: {label: Titre du menu}
        category_id: {label: Catégorie}
        
      list:
        title: Liste des pages du site
        display: [=menu_title, category_id, publication_date]
        sort: [menu_title, asc]

      filter:
        class: staticPageFormFilter
        display: [category_id, publication_date]

      form:   ~

      edit:
        title: Edition de la page "%%menu_title%%"

      new:
        title: Ajout d'une page
