generator:
  class: sfDoctrineGenerator
  param:
    model_class:           StaticPage
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          static_page
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:

      actions: ~

      fields:
        content: {label: Contenu de la page}

      list:    ~

      filter:  ~

      form:   ~

      edit:    ~

      new:     ~
