<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/03/04 11:55:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=grainedevie',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
