<?php

/**
 * BilanCarboneCoeffTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BilanCarboneCoeffTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BilanCarboneCoeffTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BilanCarboneCoeff');
    }
}