<?php

/**
 * BooleanConfigurationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BooleanConfigurationTable extends ConfigurationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object BooleanConfigurationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BooleanConfiguration');
    }
}