<?php

/**
 * CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('category');
    }

    public function getActiveCategories() //author : Laurent
    {
        $query = $this->createQuery('a')->where('a.is_activated = ?', true)->orderBy('a.position ASC');

        return $query->execute();

    }
}