<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Category extends BaseCategory {

    public static function monter(Category $category) {
        $currentPosition = $category->getPosition();
        if ($currentPosition <= 1) {
            return false;
        } else {
            $upCategory = Doctrine_Query::create()->from('category c')->whereIn('c.position', $currentPosition - 1)->leftJoin('c.Translation')->fetchOne();
            if ($upCategory != false) {
                $upCategory->setPosition($currentPosition);
                $upCategory->save();

                $category->setPosition($currentPosition - 1);
                $category->save();

                return true;
            } else {
                return false;
            }
        }
    }

    public static function descendre(Category $category) {
        $currentPosition = $category->getPosition();
        $lowCategory = Doctrine_Query::create()->from('category c')->whereIn('c.position', $currentPosition + 1)->leftJoin('c.Translation')->fetchOne();
        if ($lowCategory == false) {
            return false;
        } else {
            $lowCategory->setPosition($currentPosition);
            $lowCategory->save();

            $category->setPosition($currentPosition + 1);
            $category->save();

            return true;
        }
    }

    public static function activateToggle(Category $category) {
        $currentIsActivated = $category->getIsActivated();

        if ($currentIsActivated) {
            $category->setIsActivated(false);
            $category->save();
        } else {
            $category->setIsActivated(true);
            $category->save();
        }

        return true;
    }

    public static function getLastPosition() {
        return Doctrine_Query::create()->from('category c')->count();
    }

    public function save(Doctrine_Connection $conn = null) {
        if ($this->getPosition() == null) {
            $this->setPosition(Category::getLastPosition() + 1);
        }
        return parent::save($conn);
    }

}