<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Category extends BaseCategory {

    public static function monter(Category $category) {
        $currentPosition = $category->getPosition();
        if ($currentPosition <= 1) {
            return false;
        } else {
            $upCategory = Doctrine_Query::create()->from('category c')->whereIn('c.position', $currentPosition - 1)->leftJoin('c.Translation')->execute();

            $upCategory['0']->setPosition($currentPosition);
            $upCategory['0']->save();

            $category->setPosition($currentPosition - 1);
            $category->save();

            return true;
        }
    }

    public static function descendre(Category $category) {
        $currentPosition = $category->getPosition();
        $lowCategory =  Doctrine_Query::create()->from('category c')->whereIn('c.position', $currentPosition + 1)->leftJoin('c.Translation')->fetchOne();        
        if($lowCategory == false){
            return false;
        }else{
            $lowCategory->setPosition($currentPosition);
            $lowCategory->save();

            $category->setPosition($currentPosition+1);
            $category->save();

            return true;
        }
        
    }

}