<?php

/**
 * CitationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CitationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CitationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Citation');
    }
    public function getOneRandom($culture)
    {
    	$query = $this->createQuery('a')->innerJoin('a.Translation t')->where("t.lang=?", $culture)->andWhere("t.content != ''")->orderBy('RAND()')->limit(1);
        return $query->execute();
    }
}