<?php

/**
 * Comment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    grainedevie
 * @subpackage Laurent
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Comment extends BaseComment {

    protected $oldText;

    public function __construct($table = null, $isNewEntry = false) {
        $temp = parent::__construct($table, $isNewEntry);
        return $temp;
    }

    public function save(Doctrine_Connection $conn = null) {
        if($this->isModified()){
            $this->setUpdateAt(date('Y-m-d H:i:s'));
        }
        return parent::save($conn);
    }

}
