<?php

/**
 * ConfigurationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConfigurationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConfigurationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Configuration');
    }
}