<?php

/**
 * CorespondanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CorespondanceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CorespondanceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Corespondance');
    }
}