<?php

/**
 * CounterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CounterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CounterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Counter');
    }

    public function getCurrentData($culture)
    {
    	return $this->createQuery('a')->
    		select('a.initial_number, ROUND(TIMESTAMPDIFF(SECOND, a.initial_date, NOW())*a.flow) AS planted_trees, '.
    			   'a.flow, t.slogan_part1, t.slogan_part2, t.donation_text')->
    		innerJoin('a.Translation t')->
    		where("t.lang=?", $culture)->
    		orderBy('initial_date ASC')->
    		limit(1)->
    		execute();
    }
}