<?php

/**
 * CounterTextTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CounterTextTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object CounterTextTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('CounterText');
	}

	public function getCounterText($culture)
    {
    	return $this->createQuery('a')->
			select('a.id, t.slogan1, t.slogan2, t.donation')->
    		innerJoin('a.Translation t')->
    		where("t.lang=?", $culture)->
    		limit(1)->execute();
    }
}