<?php

/**
 * DynamicPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class DynamicPage extends BaseDynamicPage
{
	public function getUrl()
    {
        return url_for($this->getController().'/'.$this->getAction());
    }
}