<?php

/**
 * Faq
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Faq extends BaseFaq
{
    public static function monter(faq $faq) {
        $currentPosition = $faq->getPosition();
        if ($currentPosition <= 1) {
            return false;
        } else {
            $upfaq = Doctrine_Query::create()->from('faq c')->whereIn('c.position', $currentPosition - 1)->leftJoin('c.Translation')->fetchOne();
            if ($upfaq != false) {
                $upfaq->setPosition($currentPosition);
                $upfaq->save();

                $faq->setPosition($currentPosition - 1);
                $faq->save();

                return true;
            } else {
                return false;
            }
        }
    }

    public static function descendre(faq $faq) {
        $currentPosition = $faq->getPosition();
        $lowfaq = Doctrine_Query::create()->from('faq c')->whereIn('c.position', $currentPosition + 1)->leftJoin('c.Translation')->fetchOne();
        if ($lowfaq == false) {
            return false;
        } else {
            $lowfaq->setPosition($currentPosition);
            $lowfaq->save();

            $faq->setPosition($currentPosition + 1);
            $faq->save();

            return true;
        }
    }

    public static function activateToggle(faq $faq) {
        $currentIsActivated = $faq->getIsActivated();

        if ($currentIsActivated) {
            $faq->setIsActivated(false);
            $faq->save();
        } else {
            $faq->setIsActivated(true);
            $faq->save();
        }

        return true;
    }

    public static function getLastPosition() {
        return Doctrine_Query::create()->from('faq c')->count();
    }

    public function save(Doctrine_Connection $conn = null) {
        if ($this->getPosition() == null) {
            $this->setPosition(faq::getLastPosition() + 1);
        }
        return parent::save($conn);
    }
}