<?php

/**
 * FaqCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FaqCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FaqCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FaqCategory');
    }
}