<?php

/**
 * FaqTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FaqTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FaqTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Faq');
    }
}