<?php

/**
 * FolderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FolderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FolderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Folder');
    }
}