<?php

/**
 * GaleryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GaleryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GaleryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Galery');
    }
}