<?php

/**
 * GoogleAnalyticsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GoogleAnalyticsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GoogleAnalyticsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GoogleAnalytics');
    }
}