<?php

/**
 * GuestbookTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GuestbookTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GuestbookTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Guestbook');
    }
}