<?php

/**
 * GuestbookTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GuestbookTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GuestbookTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Guestbook');
    }
    public function getOneRandom($culture)
    {
    	return Doctrine_Core::getTable('guestbook')->createQuery('a')->innerJoin('a.Language l')->where("l.abbreviation=?", $culture)->andWhere("a.is_validated=?",true)->orderBy('RAND()')->limit(1)->execute();
    }
}