<?php

/**
 * LanguageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LanguageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LanguageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Language');
    }
}