<?php

/**
 * MessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Message');


    }

    public static function numberOfNewMessage($myId){
        return Doctrine_Core::getTable('Message')->createQuery()->where('reply_at IS NULL')->andWhere('forward_to_id = ?',$myId)->count();
    }

    public static function getMyMessage(){
        return Doctrine_Core::getTable('Message')->createQuery()->execute();
    }
}