<?php

/**
 * Message
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Laurent
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Message extends BaseMessage {


    public function save(Doctrine_Connection $conn = null) {
        if ($this->getCreatedAt() == null) {
            $this->setCreatedAt(date('Y-m-d H:i:s'));
        }
        return parent::save($conn);
    }

    public function getSenderName(){
        return $this->getSender()->getFirstName()." ".$this->getSender()->getLastName();
    }

    public function readed($valeur) {
        if($this->getReadAt() == null){
            $this->setReadAt($valeur);
        }
    }

}
