<?php

/**
 * NewsletterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsletterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewsletterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Newsletter');
    }
}