<?php

/**
 * Newsletter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Newsletter extends BaseNewsletter
{
	public function save(Doctrine_Connection $conn = null)
	{
		$this->setSubscriberCount(Doctrine::getTable('Subscriber')->count());

		$subscribers=Doctrine::getTable('Subscriber')->findAll();
		sfApplicationConfiguration::getActive()->loadHelpers(array('Url', 'Tag'));
		foreach($subscribers as $s)
		{
		    sfContext::getInstance()->getMailer()->composeAndSend(
		      array('info@grainedevie.seaflat.be' => 'Graine de vie'),
		      $s->getEmail(),
		      'Newsletter :'.$this->getNews()->getTitle(),
		      $this->getNews()->getContent().'<br/>'.link_to('Me désinscrire','unsuscribe',$s)
		    );
		}
		return parent::save($conn);
	}
}