<?php

/**
 * NewsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('News');
    }
    public function getLast($count,$culture)
    {
    	return Doctrine_Core::getTable('News')->createQuery('a')->leftJoin('a.Language t')->where("a.publication_date < NOW()")->andWhere("a.is_activated=?",true)->andWhere('t.abbreviation= ?',$culture)->orderBy('a.publication_date DESC')->limit($count)->execute();
    }
}