<?php

/**
 * Newsletter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Newsletter extends BaseNewsletter
{
	public function save(Doctrine_Connection $conn = null)
	{
		$this->setSubscriberCount(Doctrine::getTable('Subscriber')->count());

		$subscribers=Doctrine::getTable('Subscriber')->findAll();
		foreach($subscribers as $s)
		{

		    /*sfContext::getInstance()->getMailer()->composeAndSend(
		      array('site.graine.de.vie@gmail.com' => 'Graine de vie'),
		      $s->getEmail(),
		      $this->getNews()->getContent()
		    );*/
		}
		return parent::save($conn);
	}
}