<?php

/**
 * News
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class News extends BaseNews
{
	public function enable()
	{
		$this->setIsActivated(true);
		$this->save();
	}
	public function disable()
	{
		$this->setIsActivated(false);
		$this->save();
	}
	public function getFormatedText($lenght)
	{
		$texte=strip_tags($this->getContent());
		if (strlen($texte)>$lenght)
		{
		    // Séléction du maximum de caractères
		    $texte = substr($texte, 0, $lenght);
		    // Récupération de la position du dernier espace (afin de ne pas tronquer un mot)
		    $position_espace = strrpos($texte, " ");
		    $texte = substr($texte, 0, $position_espace);
		    $texte = $texte."...";
		}
		return $texte;
	}
}