<?php

/**
 * NewsCommentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsCommentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewsCommentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NewsComments');
    }
}