<?php

/**
 * NumericConfigurationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NumericConfigurationTable extends ConfigurationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object NumericConfigurationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NumericConfiguration');
    }
}