<?php

/**
 * PhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Photo');
    }

    public function retrieveBackendPhoto(Doctrine_Query $query) {        
        $rootAlias = $query->getRootAlias();
        $query->leftJoin($rootAlias . '.Translation');
        $query->leftJoin($rootAlias . '.Galery g')->leftJoin('g.Translation')->orderBy('position ASC');
        return $query;    
    }
}