<?php

/**
 * RefImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefImageTable extends Doctrine_Table
{
	/**
     * Returns an instance of this class.
     *
     * @return object RefImageTable
     */
	public static function getInstance()
    {
    	return Doctrine_Core::getTable('RefImage');
    }

    public static function getPersonsWithAmount()
    {
    	return Doctrine_Core::getTable('payment')->createQuery('a')->
    		select('a.id AS id, CONCAT(a.brut_amout, " €\t", b.first_name, " ", b.last_name) AS name')->
    		innerJoin('a.Person b')->execute();
    }
}