<?php

/**
 * RefImageParamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefImageParamTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefImageParamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefImageParam');
    }
}