<?php

/**
 * SloganTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SloganTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object SloganTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('Slogan');
	}

	public static function getCounterSlogans()
    {
    	return SloganTable::getInstance()->createQuery('a')->
    		select('a.name AS id, a.name AS name')->
    		where('a.type=?', 'counter')->groupBy('a.name')->execute();
    }

    public static function getRefImgSlogans()
    {
    	return SloganTable::getInstance()->createQuery('a')->
    		select('a.name AS id, a.name AS name')->
    		where('a.type=?', 'refimg')->groupBy('a.name')->execute();
    }

    public static function updateSloganNames($id, $name)
	{
		$oldName = SloganTable::getInstance()->createQuery('a')->
    		select('a.name')->where('a.id=?', $id)->
    		execute(array(), Doctrine::HYDRATE_NONE);
		
		return SloganTable::getInstance()->createQuery('a')->
    		update()->set('a.name', '?', $name)->
    		where('a.name=?', $oldName[0][0])->execute();
	}
}