<?php

/**
 * SloganTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SloganTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object SloganTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('Slogan');
	}

	public static function getSlogans()
    {
    	return SloganTable::getInstance()->createQuery('a')->
    		select('a.name AS id, a.name AS name')->groupBy('a.name')->execute();
    }
}