<?php

/**
 * StandardSentenceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StandardSentenceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StandardSentenceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StandardSentence');
    }
}