<?php

/**
 * StaticPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StaticPageTable extends PageTable {

    /**
     * Returns an instance of this class.
     *
     * @return object StaticPageTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('StaticPage');
    }

    public function getActivePages($cu) {
        $query = $this->createQuery('a')->leftJoin('a.Translation t')->where('t.is_activated = ?', true)->andWhere('t.lang = ?', $cu);
        return $query->execute();
    }

    public function retrieveBackendStaticPage(Doctrine_Query $query) {
        $rootAlias = $query->getRootAlias();
        $query->leftJoin($rootAlias . '.Category c')->leftJoin('c.Translation');
        return $query;
    }

}