<?php

/**
 * StaticPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    grainedevie
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class StaticPage extends BaseStaticPage
{
	public function getUrl()
	{
		return url_for('page', $this);
	}
	public function getTitleSlug()
	{
		return trim(preg_replace('/\W+/', '-', $this->getTitle()),'-');
	}
}