<?php

/**
 * StringConfigurationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StringConfigurationTable extends ConfigurationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object StringConfigurationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StringConfiguration');
    }
}