generator:
  class: sfDoctrineGenerator
  param:
    model_class:           faqCategory
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          faq_category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:     
        title: Liste des catégories de FAQ
        display: [=name]
        fields:
          name:
            label: Nom de la catégorie
      filter:  
        class: false
      form:    ~
      edit:    ~
      new:     ~
