# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules

sf_guard_auth_signin:
  url: /signin
  param: {module: sfGuardAuth, action: signin}

sf_guard_register:
  url: /register
  param: {module: sfGuardRegister, action: index}

homepage:
  url:   /
  param: { module: page, action: index }

localized_homepage:
  url:   /:sf_culture/
  param: { module: page, action: index}

page:
  url:   /:sf_culture/page/:id/:title_slug
  class:   sfDoctrineRoute
  options: { model: StaticPage, type: object }
  param:   { module: page, action: show }
  requirements:
    id: \d+
    sf_method: [get]

partner_show:
  url: /:sf_culture/partner/:id
  class:   sfDoctrineRoute
  options: { model: Partner, type: object }
  param:   { module: partner, action: show }
  requirements:
    id: \d+
    sf_method: [get]

default_index:
  url:   /:sf_culture/:module
  param: { action: index }

default:
  url:   /:sf_culture/:module/:action/*