# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [frontend.css, protoslider.css, jquery-ui-1.8.10.custom.css, search.css]

  javascripts:    [lib/prototype.js, lib/jquery-1.5.1.min.js, lib/jquery-ui-1.8.10.custom.min.js, lib/easel.min.js, lib/chili-1.7.pack.js, lib/jquery.easing.js, lib/jquery.dimensions.js, lib/jquery.accordion.js, protoslider/protoslider.min.js, jscounter/jscounter.min.js, global.js]

  has_layout:     true
  layout:         layout
