<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/05/05 19:00:33
sfConfig::add(array(
  'app_tinymce_options' => 'size=45x10 rich=true tinymce_options=width:580,height:350',
));
