<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/04/28 12:51:37
sfConfig::add(array(
  'app_tinymce_options' => 'size=45x10 rich=true tinymce_options=width:580,height:350',
));
