<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/03/02 14:54:50

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=grainedevie',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
