<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/05/05 19:00:34
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'AccesAdmin',
  ),
);
