<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/05/03 12:53:26
sfConfig::add(array(
  'mod_contactavances_enabled' => true,
  'mod_contactavances_view_class' => 'sfPHP',
));
