<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/05/03 14:02:37
sfConfig::add(array(
  'mod_sfguardpermission_enabled' => true,
  'mod_sfguardpermission_view_class' => 'sfPHP',
));
