generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Galery
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          galery
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Géstion de Galeries
        display: [id, name, position, is_activated]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
