generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Galery
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          galery
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        is_activated: {label: Visible, help: 'Cette gallérie est-elle visible pour les utilisateurs du site ?'}
        name: {label: Nom}
      list:    
        title: Liste de Galléries
        batch_actions: {}
        display: [=name, is_activated]
        sort: [position, asc]
        table_method: retrieveBackendGalleries
      filter:  
        class: false
      form:    ~
      edit:
        title: Edition de la gallérie "%%name%%"
      new:     
        title: Ajouter une nouvelle gallérie
