generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Folder
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          folder
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        name: {label: 'Nom'}        
      list:    
        display: [=name]
        title: Liste des dossiers
      filter:  ~
      form:    ~
      edit:    
        title: Modifier le nom d'un dossier
      new:    
        title: Creer un nouveau dossier
