generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Counter
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          counter
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Géstion du compteur d'arbres
        display: [=initial_number,=initial_date, =flow]
        fields:
          initial_number:
            label: Nombre d'arbres
          initial_date:
            label: Date
          flow:
            label: Débit (arbres/par minute)
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
