generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Counter
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          counter
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Gestion du compteur d'arbres
        batch_actions: {}
        display: [_initial_date,=initial_number,=period,=objective_number,_slogan]
        fields:
          initial_date:
            label: Date initiale
            date_format: dd-MMMM-yyyy
          initial_number:
            label: Nombre d'arbres initial
          period:
            label: Période (en mois)
          objective_number:
            label: Objectif
      filter:
        class: false
      form:    ~
      edit:
        title: Modification du compteur d'arbres
        display: [=initial_date,=initial_number,=period,=objective_number,=slogan]
        fields:
          initial_date:
            label: Date initiale
            date_format: dd-MMMM-yyyy
          initial_number:
            label: Nombre d'arbres initial
          period:
            label: Période (en mois)
          objective_number:
            label: Objectif
      new:
        title: Gestion du compteur d'arbres
        display: [=initial_date,=initial_number,=period,=objective_number,=slogan]
        fields:
          initial_date:
            label: Date initiale
            date_format: dd-MMMM-yyyy
          initial_number:
            label: Nombre d'arbres initial
          period:
            label: Période (en mois)
          objective_number:
            label: Objectif
