generator:
  class: sfDoctrineGenerator
  param:
    model_class:           category
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Liste des catégories
        display: [=name]
      filter:  ~
      form:    ~
      edit:
        title: Edition de la catégorie "%%name%%"
      new:
        title: Ajouter une nouvelle catégorie
