generator:
  class: sfDoctrineGenerator
  param:
    model_class:           category
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name: {label: Nom de la catégorie, help: Veuillez entrer le nom de la cétégorie de la langue mentionnée}
        is_activated: {label: Visible, help: Cette catégorie est-elle visible pour les utilisateurs du site}
      list:
        title: Liste des catégories
        display: [=name, _isActivated, position]
        sort: [position, asc]
      filter:
        display: [is_activated, position]
      form:   ~
      edit:
        title: Edition de la catégorie "%%name%%"
      new:
        title: Ajouter une nouvelle catégorie
