## author: Laurent
sf_guard_forgot_password:
  url: /forgotpassword
  param: {module: sfGuardForgotPassword, action: index}

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_logout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }