generator:
  class: sfDoctrineGenerator
  param:
    model_class:           News
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          news
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        language_id:
          label: Langue
        flag:
          label: Langue
        title:
          label: Titre
        publication_date:
          label: Date de publication
        is_activated:
          label: Status
      list:
        title: Liste des news :
        display: [_flag, =title, _publication_date, _is_activated]
        batch_actions: {}
      filter:
        display: [language_id, title]
      form:    ~
      edit:    ~
      new:
        title: Ecrire une news
