<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/05/05 19:00:25

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=grainedevie',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
