Language:
  actAs: {Timestampable: ~}
  columns:
    name: {type: string(40), notnull: true, unique: true}
    abbreviation: {type: string(5), notnull: true, unique: true}
    flag: {type: string(255)}
    is_activated: {type: boolean, notnull: true, default: false}
    is_default: {type: boolean, notnull: true, unique: false}

Category:
  actAs: {Timestampable: ~, I18n: {fields: [name]}}

  columns:
    name: {type: string(40), notnull: true, unique: true}
    position: {type: integer, notnull: true}
    is_activated: {type: boolean, notnull: true, default: false}

Page:
  actAs: {Timestampable: ~}
  actAs: {I18n: {fields: [menu_title, content, is_activated, title]}}
  columns:
    menu_title: {type: string(255), notnull: true}
    position: {type: integer, notnull: true}
    publication_date: {type: timestamp}
    category_id: {type: integer}
  relations:
    Category: {local: category_id, foreign: id}

StaticPage:
  inheritance: {type: concrete, extends: Page}
  columns:
    content: {type: text, notnull: true}
    is_activated : {type: boolean, default: 0}
    title: {type: string(255), notnull: true}

Configuration:
  columns:
    main: {type: string(255), notnull: true}
    name: {type: string(255), notnull: true}
    description: {type: text}
    configuration_id: {type: integer}
  relations:
    BooleanConfiguration: {local: configuration_id, foreign: id}

BooleanConfiguration:
  inheritance: {type: column_aggregation, extends: Configuration, keyValue:1}
  columns:
    is_kernel: {type: boolean, default: 0}
    is_activated: {type: boolean, default: 0}

NumericConfiguration:
  inheritance: {type: column_aggregation, extends: Configuration, keyValue:2}
  columns:
    value: {type: integer, default:0}

DynamicPage:
  inheritance: {type: concrete, extends: Page}
  columns:
    controller: {type: string(255), notnull: true}
    action : {type: string(255), notnull: true}
    boolean_configuation_id: {type: integer, notnull: true}
  relations:
    BooleanConfiguration: {local: boolean_configuation_id, foreign: id}

Citation:
  actAs: {I18n: {fields: [author, content]}}
  columns:
    author: {type: string(255)}
    content: {type: text}
    
Comment:
  columns:
    text: {type: text, notnull: true}
    update_at: {type: date, notnull: true}
    
Message:
  columns:
    text: {type: text, notnull: true}
    is_saved: {type: boolean, default: 0}
    read_at: {type: date}
    created_at: {type: date, notnull: true}
    reply_at: {type: date}
    comment_id: {type: integer}
  relations:
    Comment: {local: comment_id, foreign: id}

Person:
  columns:
    first_name: {type: string(255)}
    last_name: {type: string(255)}
    email_address: {type: string(255), notnull: true, unique: true}
