Language:
  actAs: {Timestampable: ~}
  columns:
    name: {type: string(40), notnull: true, unique: true}
    abbreviation: {type: string(5), notnull: true, unique: true}
    flag: {type: string(255)}
    is_activated: {type: boolean, notnull: true, default: false}
    is_default: {type: boolean, notnull: true, unique: false}

Category:
  actAs: {Timestampable: ~, I18n: {fields: [name]}}

  columns:
    name: {type: string(40), notnull: true, unique: true}
    position: {type: integer, notnull: true, default: 99}
    is_activated: {type: boolean, notnull: true, default: false}

Page:
  actAs: {Timestampable: ~}
  columns:
    hash_code: {type: string(255), notnull: true}
    menu_title: {type: string(255), notnull: true}
    position: {type: integer, notnull: true, default: 99}
    publication_date: {type: timestamp}
    category_id: {type: integer, notnull: true}
    language_id: {type: integer, notnull: true}
  relations:
    Category: {local: category_id, foreign: id}
    Language: {local: language_id, foreign: id}

StaticPage:
  inheritance: {type: concret, extends: Page}
  columns:
    content: {type: text, notnull: true, default: "Page en construction"}
    is_activated : {type: boolean, notnull: true, default: 0}
    title: {type: string(255), notnull: true, default: "En contruction"}

DynamicPage:
  inheritance: {type: concret, extends: Page}
  colunms:
    controller: {type: string(255), notnull: true}
    action : {type: string(255), notnull: true}
    boolean_configuation_id: {type: integer, notnull: true}
  relations:
    BooleanConfiguration: {local: boolean_configuation_id, foreign: id}

Configuration:
  columns:
    name: {type: string(255), notnull: true, unique: true}
    description: {type: text}
    parent_id: {type: integer}
  relations:
    BooleanConfiguration: {local: parent_id, foreign: id}


BooleanConfiguration:
  inheritance: {type: concret, extends: Configuration}
  columns:
    is_kernel: {type: boolean, notnull: true, default: 0}
    is_activated: {type: boolean, notnull: true, default: 0}

BooleanConfiguration:
  inheritance: {type: concret, extends: Configuration}
  columns:
    value: {type: integer, notnull: true}