Language:
  actAs: {Timestampable: ~}
  columns:
    name: {type: string(40), notnull: true, unique: true}
    abbreviation: {type: string(5), notnull: true, unique: true}
    flag: {type: string(255)}
    is_activated: {type: boolean, notnull: true, default: false}
    is_default: {type: boolean, notnull: true, unique: false}

Category:
  actAs: {Timestampable: ~, I18n: {fields: [name]}}

  columns:
    name: {type: string(40), notnull: true, unique: true}
    position: {type: integer, notnull: true}
    is_activated: {type: boolean, notnull: true, default: false}

Page:
  actAs:
    Timestampable: ~
    I18n: {fields: [menu_title, content, is_activated, title]}
  columns:
    menu_title: {type: string(255), notnull: true}
    position: {type: integer, notnull: true}
    publication_date: {type: timestamp}
    category_id: {type: integer}
  relations:
    Category: {local: category_id, foreign: id}

StaticPage:
  inheritance: {type: concrete, extends: Page}
  columns:
    content: {type: text, notnull: true}
    is_activated : {type: boolean, default: 0}
    title: {type: string(255), notnull: true}

Configuration:
  columns:
    main: {type: string(255), notnull: true}
    name: {type: string(255), notnull: true}
    description: {type: text}
    configuration_id: {type: integer}
  relations:
    BooleanConfiguration: {local: configuration_id, foreign: id}

BooleanConfiguration:
  inheritance: {type: column_aggregation, extends: Configuration, keyValue:1}
  columns:
    is_kernel: {type: boolean, default: 0}
    is_activated: {type: boolean, default: 0}

NumericConfiguration:
  inheritance: {type: column_aggregation, extends: Configuration, keyValue:2}
  columns:
    value: {type: integer, default:0}

DynamicPage:
  inheritance: {type: concrete, extends: Page}
  columns:
    route: {type: string(255), notnull: true}
    boolean_configuation_id: {type: integer, notnull: true}
  relations:
    BooleanConfiguration: {local: boolean_configuation_id, foreign: id}

Citation:
  actAs: {I18n: {fields: [author, content]}}
  columns:
    author: {type: string(255)}
    content: {type: text}

Partner:
  actAs: {I18n: {fields: [company_name, description, site, is_visible]}}
  columns:
    company_name: {type: string(255)}
    logo: {type: string(255)}
    description: {type: string(255)}
    site: {type: string(255)}
    is_visible: {type: boolean, default: 0}
    position: {type: integer}
    visit_count: {type:integer, default: 0}

Galery:
  actAs: {Timestampable: ~, I18n: {fields: [name]}}
  columns:
    name: {type: string(40), notnull: true, unique: true}
    position: {type: integer, notnull: true}
    is_activated: {type: boolean, notnull: true, default: false}

Photo:
  actAs: {Timestampable: ~, I18n: {fields: [title, description] }}
  columns:
    title: {type: string(255)}
    url: {type: string(255)}
    description: {type: text}
    publication_start: {type: timestamp}
    publication_end: {type: timestamp}
    galery_id: {type: integer}
  relations:
    Galery: {local: galery_id, foreign: id}

Guestbook:
  actAs: 
    Timestampable: ~
  columns:
    content: {type: text}
    is_validated: {type: boolean, notnull: true, default: false}
    language_id: {type: integer}
  relations:
    Language: {local: language_id, foreign: id}