Language:
  actAs: {Timestampable: ~}
  columns:
    name: {type: string(40), notnull: true, unique: true}
    abbreviation: {type: string(5), notnull: true, unique: true}
    flag: {type: string(255)}
    is_activated: {type: boolean, notnull: true, default: false}
    is_default: {type: boolean, notnull: true, unique: false}

Category: #Laurent
  actAs: {Timestampable: ~, I18n: {fields: [name]}}
  columns:
    name: {type: string(40), notnull: true, unique: true}
    position: {type: integer, notnull: true}
    is_activated: {type: boolean, notnull: true, default: false}

Page:
  actAs:
    Timestampable: ~
    I18n: {fields: [menu_title, content, is_activated, title]}
  columns:
    menu_title: {type: string(255), notnull: true}
    position: {type: integer, notnull: true}
    publication_date: {type: timestamp}
    category_id: {type: integer}
  relations:
    Category: {local: category_id, foreign: id}

StaticPage: #Laurent
  inheritance: {type: concrete, extends: Page}
  columns:
    content: {type: text, notnull: true}
    is_activated : {type: boolean, default: 0}
    title: {type: string(255), notnull: true}

Configuration:
  columns:
    main: {type: string(255), notnull: true}
    name: {type: string(255), notnull: true}
    description: {type: text}
    configuration_id: {type: integer}
  relations:
    BooleanConfiguration: {local: configuration_id, foreign: id}

BooleanConfiguration:
  inheritance: {type: column_aggregation, extends: Configuration, keyValue:1}
  columns:
    is_kernel: {type: boolean, default: 0}
    is_activated: {type: boolean, default: 0}

NumericConfiguration:
  inheritance: {type: column_aggregation, extends: Configuration, keyValue:2}
  columns:
    value: {type: integer, default:0}

StringConfiguration:
  inheritance: {type: column_aggregation, extends: Configuration, keyValue:3}
  columns:
    value: {type: string(255), default:0}

DynamicPage:
  inheritance: {type: concrete, extends: Page}
  columns:
    controller: {type: string(255), notnull: true}
    action: {type: string(255), notnull: true}
    boolean_configuation_id: {type: integer, notnull: true}
  relations:
    BooleanConfiguration: {local: boolean_configuation_id, foreign: id}

Citation:
  actAs: {I18n: {fields: [author, content]}}
  columns:
    author: {type: string(255)}
    content: {type: text}

Comment: #Laurent
  columns:
    text: {type: text}
    update_at: {type: datetime}

Message: #Laurent
  columns:
    text: {type: text, notnull: true}
    is_saved: {type: boolean, default: 0}
    read_at: {type: datetime}
    created_at: {type: datetime, notnull: true}
    reply_at: {type: datetime}
    comment_id: {type: integer}
    sender_id: {type: integer}
    category_id: {type: integer, notnull: true}
    folder_id: {type: integer, notnull: true, default: 1}
    forward_to_id : {type: integer, notnull: true}
  relations:
    Comment: {local: comment_id, foreign: id, alias: comment, foreignType: one}
    Sender: {class: Person, local: sender_id, foreign: id}
    FaqCategory: {local: category_id, foreign: id, alias: faqCategory, foreignType: one}
    Folder: {local: folder_id, foreign: id}
    ForwardTo: {local: forward_to_id, foreign: id, class: Person}


Person: #Laurent
  columns:
    first_name: {type: string(255), notnull: true}
    last_name: {type: string(255), notnull: true}
    email_address: {type: string(255), notnull: true, unique: true}
    corespondance_id: {type: integer}
  relations:
    Corespondance: {local: corespondance_id, foreign: id}

Corespondance: #Laurent
  columns:
    first_mail: {type: datetime}
    last_mail: {type: datetime}
    number_of_mail: {type: integer, default: 0}


Partner:
  actAs: {I18n: {fields: [company_name, description, site, is_visible]}}
  columns:
    company_name: {type: string(255)}
    logo: {type: string(255)}
    description: {type: string(255)}
    site: {type: string(255)}
    is_visible: {type: boolean, default: 0}
    position: {type: integer}
    visit_count: {type: integer, default: 0}

FaqCategory:
  actAs: {I18n: {fields: [name]}}
  columns:
    name: {type: string(255)}

Faq:
  actAs: {I18n: {fields: [question, answer, is_activated]}}
  columns:
    question: {type: text}
    answer: {type: text}
    position: {type: integer}
    is_activated: {type: boolean, default: 0}
    faq_category_id: {type: integer, notnull: true}
  relations:
    faqCategory: {local: faq_category_id, foreign: id}

Galery:
  actAs: {I18n: {fields: [name]}}
  columns:
    name: {type: string(40), notnull: true, unique: true}
    position: {type: integer, notnull: true}
    is_activated: {type: boolean, notnull: true, default: false}

Photo:
  actAs: {Timestampable: ~, I18n: {fields: [title, description] }}
  columns:
    title: {type: string(255)}
    url: {type: string(255)}
    description: {type: text}
    publication_start: {type: timestamp}
    publication_end: {type: timestamp}
    galery_id: {type: integer}
  relations:
    Galery: {local: galery_id, foreign: id}

Counter:
  actAs: {I18n: {fields: [slogan_part1, slogan_part2, donation_text]}}
  columns:
    initial_date: {type: timestamp, notnull: true}
    initial_number: {type: integer, notnull: true}
    period: {type: integer, notnull: true}
    objective_number: {type: integer, notnull: true}
    slogan_part1: {type: string(255), notnull: true}
    slogan_part2: {type: string(255), notnull: true}
    donation_text: {type: string(255), notnull: true}

Guestbook:
  actAs: 
    Timestampable: ~
  columns:
    content: {type: text}
    is_validated: {type: boolean, notnull: true, default: false}
    language_id: {type: integer}
  relations:
    Language: {local: language_id, foreign: id}

News:
  columns:
    title: {type: varchar(255)}
    content: {type: text}
    is_activated: {type: boolean, notnull: true, default: false}
    language_id: {type: integer, notnull: true}
    publication_date: {type: timestamp}
    comments_activated: {type: boolean, notnull: true, default: true}
  relations:
    Language: {local: language_id, foreign: id}

NewsComments:
  actAs:
    Timestampable: ~
  columns:
    content: {type: text}
    author_id: {type: integer, notnull: true}
    news_id: {type: integer, notnull: true}
    father_id: {type: integer}
  relations:
    News: {local: news_id, foreign: id}
    Comments: {local: father_id, foreign: id}
    sfGuardUser: {local: author_id, foreign: id}

Folder:
  columns:
    name: {type: string(255), unique: true}

StandardSentence:
  columns:
    text: {type: text, notnull: true}
    title: {type: string(255), notnull: true}

Subscriber:
  columns:
    email: {type: string(255), unique: true}
    hash: {type: string(255)}

Newsletter:
  actAs:
    Timestampable: ~
  columns:
    news_id: {type: integer, notnull: true}
    subscriber_count: {type: integer}
  relations:
    News: {local: news_id, foreign: id}

payment:
  columns:
    brut_amout: {type: float, notnull: true}
    fee: {type: float, notnull: true}
    date: {type: string(255), notnull: true}
    paypal_id: {type: string(255), notnull: true, unique: true}
    person_id: {type: integer}
  relations:
    Person: {local: person_id, foreign: id}

address:
  columns:
    street: {type: string(255), notnull: true}
    country: {type: string(255), notnull: true}
    city: {type: string(255), notnull: true}
    zip_code: {type: string(10), notnull: true}
    person_id: {type: integer}
  relations:
    Person: {local: person_id, foreign: id}
