generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Message
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          contactavances
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~

      fields:
        created_at: {label: "Envoyé le"}
        sender_name: {label: "Expéditeur"}
        faq_category: {label: "Catégorie"}
        read_at: {label: "Lu le"}
        category_id: {label: "Catégorie"}
        text: {label: "Message"}
        comment: {label: "Commentaire", help: "N'est pas visible pour l'expéditeur mais seulement par les admins"}
        is_saved: {label: "Voulez-vous conserver ce message ?"}

      list:
        title: Liste des messages
        display: [=sender_name, faq_category, created_at, read_at]
        sort: [read_at, desc]


      filter:
        class: false

      form:
        class: MessageAdminForm

      new:     ~

      edit:  ~
        