## YAML Template.
---
default:
  javascripts: [lib/jquery-1.5.1.min.js, lib/functionsMessages/foldersManagement.js, lib/jquery.lightbox_me.js, lib/functionsMessages/folders.js]
  stylesheets:    [ssMessages/foldersManagement.css, admin.css]